apiVersion: v1
kind: Pod
metadata:
  name: dan
  labels:
    app: httpd
  namespace: test-pipeline
spec:
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: httpd
      image: 'image-registry.openshift-image-registry.svc:5000/test-pipeline/rhdh-test:0.0.2'
      command: ['sleep', '10000']
