name: RHDH Plugin Certification Catalog Update

on:
  push:
    branches:
      - main
    paths:
      - 'publishers/**/package.yaml'
  workflow_dispatch:

jobs:
  detect-changes:
    name: Detect PR Changes
    runs-on: ubuntu-latest
    outputs:
      modified_files: ${{ steps.changed-files.outputs.all_changed_files }}
      publisher_name: ${{ steps.extract-plugin.outputs.publisher_name }}
      plugin_name: ${{ steps.extract-plugin.outputs.plugin_name }}
      package_yaml: ${{ steps.extract-plugin.outputs.package_yaml }}
      version: ${{ steps.extract-plugin.outputs.version }}
    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Identify modified plugin files
      - name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          files: publishers/**/package.yaml

      - name: Extract Plugin Name and Package.yaml Path
        id: extract-plugin
        run: |
          file="${{ steps.changed-files.outputs.all_changed_files }}"


          # Commited package string
          package=$(yq e '.global.dynamic.plugins[0].package' "$file")
          IMAGE_LOC="${package%:*}"
          # PLUGIN_VERSION: everything after the last colon
          PLUGIN_VERSION="${package##*:}"

          echo "Processing file: $file"
          echo "publisher_name=$(echo "$file" | cut -d'/' -f2)" >> $GITHUB_OUTPUT
          echo "plugin_name=$(echo "$file" | cut -d'/' -f3)" >> $GITHUB_OUTPUT
          echo "package_yaml=$file" >> $GITHUB_OUTPUT
          echo "version=$(echo "$file" | cut -d'/' -f4)" >> $GITHUB_OUTPUT
          echo "image_loc=$IMAGE_LOC" >> "$GITHUB_OUTPUT"
          echo "plugin_version=$PLUGIN_VERSION" >> "$GITHUB_OUTPUT"

      - name: Append plugin entry if not present
        run: |
          FILE=certified-plugins.yaml
          OWNERS="${OWNERS:-${GITHUB_ACTOR}}"

          echo "Checking for existing plugin entry..."
          exists=$(yq e ".certified[] | select(.name == \"$PLUGIN_NAME\" and .image_loc == \"$IMAGE\")" "$FILE")

          if [ -z "$exists" ]; then
            echo "Appending new plugin entry..."

            yq e -i '
              .certified += [{
                "name": env(PLUGIN_NAME),
                "authors": env(AUTHORS),
                "owners": env(OWNERS),
                "image_loc": env(IMAGE),
                "plugin_version": env(VERSION),
                "rhdh_version": null
              }]
            ' "$FILE"
          else
            echo "Plugin already exists. Skipping append."
          fi

          echo "Test file Output"
          cat $FILE 
        env:
          PLUGIN_NAME: ${{ steps.extract-plugin.outputs.plugin_name }}
          AUTHORS: ${{ steps.extract-plugin.outputs.publisher_name }}
          OWNERS: dcurran90
          IMAGE: ${{ steps.extract-plugin.outputs.image_loc }}
          VERSION: ${{ steps.extract-plugin.outputs.plugin_version }}


      - name: Append to HTML Output
        run: |
          PUBLISHER_NAME="${{ needs.detect-changes.outputs.publisher_name }}"
          PLUGIN_NAME="${{ needs.detect-changes.outputs.plugin_name }}"
          PACKAGE_YAML="${{ needs.detect-changes.outputs.package_yaml }}"
          VERSION="${{ needs.detect-changes.outputs.version }}"
          
          cat <<EOF > new_output.html
          <p>Publisher Name: $PUBLISHER_NAME</p>
          <p>Version: $VERSION</p>
          <p>Plugin Name: $PLUGIN_NAME</p>
          <p>Package repo path: https://github.com/redhat-developer/rhdh-plugin-certification/blob/rose-branch/$PACKAGE_YAML</p>
          EOF
      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add new_output.html
          git add certified-plugins.yaml
          git commit -m "Post-merge catalog updates"
          git push

      - name: Upload Plugin Metadata
        uses: actions/upload-artifact@v4
        with:
          name: plugin-metadata
          path: new_output.html
        
 